CREATE TABLE Aircraft (
	Id INT NOT NULL IDENTITY(1,1),
	Description VARCHAR(50) NOT NULL,
	RegNoId VARCHAR(10),
	Active BIT NOT NULL CONSTRAINT DF_Aircraft_Active DEFAULT (1),
	CreatedDateTime DATETIME CONSTRAINT DF_Aircraft_CreatedDateTime DEFAULT (GETDATE()),
	LastModifiedDateTime DATETIME CONSTRAINT DF_Aircraft_LastModifiedDateTime DEFAULT (GETDATE()),
	CONSTRAINT PK_Aircraft_Id PRIMARY KEY (Id),
	CONSTRAINT UQ_Aircraft_Description UNIQUE (Description)
);

CREATE TABLE EngineTrend (
	Id INT NOT NULL IDENTITY(1,1),
	AircraftId INT NOT NULL,
	TailVolumeInLitres DECIMAL(6,2),
	CollectionDate DATE NOT NULL,
	FlightHours INT NOT NULL,
	FlightCycles INT,
	OutsideAirTemperatureInCelsius DECIMAL(6,2),
	AltitudeInFeet DECIMAL(8,2),
	AirspeedInKnots DECIMAL(5,2),
	InterstageTurbineTemperatureInCelsius DECIMAL(6,2),
	TorqueInPsi DECIMAL(6,2),
	PropellerRotationInRpm DECIMAL(6,2),
	NGCompressorRotationSpeedPerc DECIMAL(5,2),
	FuelFlowInLitres DECIMAL(5,2),
	OilTemperatureInCelsius DECIMAL(6,2),
	OilPressureInPsi DECIMAL(5,2),
	FuelPressureInPsi DECIMAL(5,2),
	Active BIT NOT NULL CONSTRAINT DF_EngineTrend_Active DEFAULT (1),
	CreatedDateTime DATETIME NOT NULL CONSTRAINT DF_EngineTrend_CreatedDateTime DEFAULT (GETDATE()),
	LastModifiedDateTime DATETIME NOT NULL CONSTRAINT DF_EngineTrend_LastModifiedDateTime DEFAULT (GETDATE()),
	CONSTRAINT PK_EngineTrend_Id PRIMARY KEY (Id),
	CONSTRAINT FK_EngineTrend_AircraftId_Aircraft_Id FOREIGN KEY (AircraftId) REFERENCES Aircraft (Id),
	CONSTRAINT UQ_EngineTrend_AircraftId_CollectionDate_FlightHours UNIQUE (AircraftId, CollectionDate, FlightHours),
	CONSTRAINT CHK_EngineTrend_TailVolumeInLitres CHECK (TailVolumeInLitres >= 0 AND TailVolumeInLitres <= 1500),
	CONSTRAINT CHK_EngineTrend_FlightHours CHECK (FlightHours >= 0),
	CONSTRAINT CHK_EngineTrend_FlightCycles CHECK (FlightCycles >= 0),
	CONSTRAINT CHK_EngineTrend_InterstageTurbineTemperatureInCelsius CHECK (InterstageTurbineTemperatureInCelsius >= 400 AND InterstageTurbineTemperatureInCelsius <= 725),
	CONSTRAINT CHK_EngineTrend_TorqueInPsi CHECK (TorqueInPsi >= 0 AND TorqueInPsi <= 1625),
	CONSTRAINT CHK_EngineTrend_PropellerRotationInRpm CHECK (PropellerRotationInRpm >= 0 AND PropellerRotationInRpm <= 2200),
	CONSTRAINT CHK_EngineTrend_NGCompressorRotationSpeedPerc CHECK (NGCompressorRotationSpeedPerc >= 50 AND NGCompressorRotationSpeedPerc <= 100),
	CONSTRAINT CHK_EngineTrend_FuelFlowInLitres CHECK (FuelFlowInLitres >= 51 AND FuelFlowInLitres <= 243),
	CONSTRAINT CHK_EngineTrend_OilTemperatureInCelsius CHECK (OilTemperatureInCelsius >= 100 AND OilTemperatureInCelsius <= 220),
	CONSTRAINT CHK_EngineTrend_OilPressureInPsi CHECK (OilPressureInPsi >= 40 AND OilPressureInPsi <= 100),
	CONSTRAINT CHK_EngineTrend_FuelPressureInPsi CHECK (FuelPressureInPsi >= 5 AND FuelPressureInPsi <= 25)
);